name: Cloudflare R2 - Dev

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [cf-development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: cf-development
      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
      - name: Install Dependencies
        working-directory: ./ui-app/client
        run: npm i
      - name: Building to JS
        working-directory: ./ui-app/client
        run: npm run cf
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: r2 object put dev-static/js/dist/index.js --file=ui-app/client/dist/index.js --cache-control "public,max-age=3600"
      - name: Without action
        run: npx wrangler r2 object put dev-static/js/dist/index.js.map --file=ui-app/client/dist/index.js.map --cache-control "public,max-age=3600"
