name: Cloudflare R2 - Dev

on:
  workflow_dispatch:
  push:
    branches: [cf-development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: cf-development
      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
      - name: Install Dependencies
        working-directory: ./ui-app/client
        run: npm i
      - name: Building to JS
        working-directory: ./ui-app/client
        run: npm run cf
      - name: Configure AWS credentials with Cloudflare credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          aws-region: auto
      - name: Deploy
        run: aws s3 sync --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com ./ui-app/client/dist s3://dev-static/js/dist/
