name: Cloudflare R2 - Prod

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [cf-production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: cf-production
      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
      - name: Install Dependencies
        working-directory: ./ui-app/client
        run: npm i
      - uses: cloudposse/github-action-jq@main
        name: Installing jq
        with:
          compact: true
          input: '["test", "test2", "test3"]'
          script: |-
            map(select(. == "test"))
      - name: Building to JS
        working-directory: ./ui-app/client
        run: npm run cf
      - name: Pushing to Cloudflare
        working-directory: ./ui-app/client
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          find dist -name "*.js" -type f -exec npx wrangler r2 object put prod-static/js/{} --file={} --content-type text/javascript --cache-control="public,max-age=3600" \;
          find dist -name "*.css" -type f -exec npx wrangler r2 object put prod-static/js/{} --file={} --content-type text/css --cache-control="public,max-age=3600" \;
          find dist -name "*.html" -type f -exec npx wrangler r2 object put prod-static/js/{} --file={} --content-type text/html --cache-control="public,max-age=3600" \;
          find dist -name "*.json" -type f -exec npx wrangler r2 object put prod-static/js/{} --file={} --content-type application/json --cache-control="public,max-age=3600" \;
          echo "JSON prepared :"
          find dist -type f | jq -Rs '{"files": split("\n")[:-1] | map("https://cdn.modlix.com/js/" + .)}'
          echo "Calling purge for cdn.modlix.com:"
          find dist -type f | jq -Rs '{"files": split("\n")[:-1] | map("https://cdn.modlix.com/js/" + .)}' | curl -s -X POST -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" -H "Content-Type: application/json" -d @- https://api.cloudflare.com/client/v4/zones/ae81e53db5aca470c4e4073aa03498cd/purge_cache
