name: AWS S3 - Dev

on:
  workflow_dispatch:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      - name: Setting up node
      - uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
      - name: Install Dependencies
        working-directory: ./client
        run: npm ci
      - name: Building to JS
        working-directory: ./client
        run: npm run aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy
        run: aws s3 sync ./client/dist s3://nclc-dev
