name: AWS S3 - Stage

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
      - name: Install Dependencies
        working-directory: ./ui-app/client
        run: npm i
      - name: Building to JS
        working-directory: ./ui-app/client
        run: npm run aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy
        run: aws s3 sync ./ui-app/client/dist s3://nclc-stage
      - name: Cache Clear
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://stage.modlix.com/api/ui/cache/jsCache
          method: "DELETE"
